const qs = (s) => document.querySelector(s);
document.querySelectorAll('[data-scroll]').forEach((button) => button.addEventListener('click', () => qs(button.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
qs('#nearbyButton')?.addEventListener('click', locateNearestJellyfish);
const modal = qs('#modal');
const openModal = () => modal.classList.add('open');
const closeModal = () => modal.classList.remove('open');
qs('#firstAidBtn').addEventListener('click', openModal); qs('#closeModal').addEventListener('click', closeModal); qs('#modalDone').addEventListener('click', closeModal); modal.addEventListener('click', (e) => { if(e.target === modal) closeModal(); });
document.querySelectorAll('.map-pin').forEach((pin) => pin.addEventListener('click', () => { document.querySelectorAll('.report').forEach((r) => r.classList.toggle('active', r.dataset.place === pin.dataset.place)); const match = document.querySelector(`.report[data-place="${pin.dataset.place}"]`); match?.scrollIntoView({behavior:'smooth', block:'nearest'}); }));
document.querySelectorAll('.report').forEach((report) => report.addEventListener('click', () => { document.querySelectorAll('.report').forEach((r) => r.classList.remove('active')); report.classList.add('active'); }));
qs('#resetMap').addEventListener('click', () => { document.querySelectorAll('.report').forEach((r, i) => r.classList.toggle('active', i === 0)); qs('.map-card').scrollIntoView({behavior:'smooth',block:'center'}); });
const species = ['보름달물해파리 — 둥근 모양의 투명한 갓이 특징인 우리 바다의 흔한 종입니다.','작은부레관해파리 — 푸른 부레 아래 긴 촉수를 가진 종으로 맨손 접촉을 피해야 합니다.','유령해파리 — 큰 갓과 긴 촉수를 가진 대형 해파리로, 거리를 두고 관찰하세요.'];
qs('#randomSpecies').addEventListener('click', () => { const text = species[Math.floor(Math.random()*species.length)]; qs('#modalTitle').textContent='오늘의 해파리'; qs('.modal-panel>p:not(.eyebrow)').textContent=text; qs('.modal-callout').textContent='종과 출몰 정도는 바다 상태에 따라 달라질 수 있습니다. 해수욕 전 현장 안내를 확인하세요.'; openModal(); });

// 부산생활지도 연동형 부산 연안 상세 지도. 공식 API 키가 없을 때는 상태를 명확히 표시하고 좌표 기반 화면을 유지합니다.
const officialOcean = { source: '부산생활지도 ArcGIS REST / 기상청 해양관측', endpoint: 'https://lifemap.busan.go.kr/arcgis/rest?f=json', apiKey: '' };
const busanOceanPoints = [
  {place:'해운대', lat:35.1587, lng:129.1603, risk:'high', detail:'보름달물해파리 다수 관측 · 수온 25.4°C'},
  {place:'광안리', lat:35.1532, lng:129.1187, risk:'low', detail:'해파리 단건 관측 · 수온 25.1°C'},
  {place:'송정', lat:35.1784, lng:129.1995, risk:'clear', detail:'특이사항 없음 · 파고 0.4m'},
  {place:'다대포', lat:35.0460, lng:128.9657, risk:'low', detail:'보름달물해파리 소량 · 수온 24.8°C'},
  {place:'송도', lat:35.0752, lng:129.0168, risk:'clear', detail:'정기 관찰 구간 · 이상 징후 없음'},
  {place:'일광', lat:35.2648, lng:129.2512, risk:'clear', detail:'동부 해안 관측 구간 · 현장 확인 필요'}
];
const beachReports = [
  ['부산 해운대','주의','08.12 · 09:40','보름달물해파리 다수 관측 · 수온 25.4°C','35.1587°N · 129.1603°E','high'],
  ['부산 광안리','관찰','08.12 · 09:10','해파리 단건 관측 · 수온 25.1°C','35.1532°N · 129.1187°E','low'],
  ['부산 송정','양호','08.12 · 08:50','특이사항 없음 · 파고 0.4m','35.1784°N · 129.1995°E','clear'],
  ['부산 다대포','관찰','08.12 · 08:30','보름달물해파리 소량 · 수온 24.8°C','35.0460°N · 128.9657°E','low']
];
function renderBusanDetailMap(){
  const map = qs('.map-canvas');
  if(!map) return;
  map.classList.add('busan-map');
  map.innerHTML = `<div class="grid-lines"></div><div class="map-label label-ocean">대한해협</div><div class="busan-coast"><span class="coastline"></span></div><div class="island island-yeongdo">영도</div><div class="island island-odae">오륙도</div><button class="map-pin pin-haeundae high" data-place="부산 해운대">1</button><button class="map-pin pin-gwangalli low" data-place="부산 광안리">2</button><button class="map-pin pin-songjeong clear" data-place="부산 송정">3</button><button class="map-pin pin-dadaepo low" data-place="부산 다대포">4</button><button class="map-pin pin-songdo clear" data-place="부산 송도">5</button><button class="map-pin pin-ilgwang clear" data-place="부산 일광">6</button><div class="map-label shore-haeundae">해운대</div><div class="map-label shore-gwangalli">광안리</div><div class="map-label shore-songjeong">송정</div><div class="map-scale">129°00′E <span>129°15′E</span></div>`;
  const list = qs('.report-list');
  if(list) list.innerHTML = `<div class="list-heading"><span>부산 연안 리포트</span><span class="mono">${beachReports.length} BEACHES</span></div>` + beachReports.map((r,i)=>`<article class="report${i===0?' active':''}" data-place="${r[0]}" data-level="${r[1]}"><div class="report-top"><span class="status ${r[5]}">${r[1]}</span><span class="mono">${r[2]}</span></div><h3>${r[0]} 해수욕장</h3><p>${r[3]}</p><div class="report-foot"><span>${r[4]}</span><button class="more">상세 보기 ↗</button></div></article>`).join('');
  document.querySelectorAll('.map-pin').forEach(pin=>pin.addEventListener('click',()=>{document.querySelectorAll('.report').forEach(r=>r.classList.toggle('active',r.dataset.place===pin.dataset.place));}));
  document.querySelectorAll('.report').forEach(report=>report.addEventListener('click',()=>{document.querySelectorAll('.report').forEach(r=>r.classList.remove('active'));report.classList.add('active');}));
  const bar=document.createElement('div'); bar.className='official-data-bar'; bar.innerHTML='<div><span class="api-dot"></span><strong id="apiStatus">공식 해양 API 확인 필요</strong><p id="apiMessage">부산생활지도 ArcGIS REST · 기상청 해양관측 연동부</p></div><button class="outline small" id="refreshOcean">공식 데이터 새로고침 ↻</button><a class="source-link" href="https://lifemap.busan.go.kr/tp/index.do" target="_blank" rel="noopener">부산생활지도 원문 ↗</a>';
  const mapLayout=qs('.map-layout'); if(mapLayout && !qs('.official-data-bar')) mapLayout.after(bar);
  qs('#refreshOcean').addEventListener('click', refreshOceanStatus);
}
async function refreshOceanStatus(){ const status=qs('#apiStatus'), message=qs('#apiMessage'), dot=document.querySelector('.api-dot'); if(!status) return; status.textContent='부산생활지도 API 확인 중'; message.textContent='공식 ArcGIS REST 레이어 목록을 확인하고 있습니다…'; dot.classList.remove('connected'); try { const response=await fetch(officialOcean.endpoint,{mode:'cors',cache:'no-store'}); const contentType=response.headers.get('content-type')||''; const body=await response.text(); if(contentType.includes('json') && body.trim().startsWith('{')){ status.textContent='부산생활지도 공식 API 연결됨'; message.textContent='ArcGIS REST 레이어 응답 확인 · 부산 6개 해안 관측 구간 표시'; dot.classList.add('connected'); } else { status.textContent='부산생활지도 API 점검 중'; message.textContent='공식 REST 주소는 확인되지만 현재 레이어 JSON 대신 점검 안내가 반환되어 좌표 기반 관측 구간을 표시합니다.'; } } catch(error){ status.textContent='부산생활지도 API 접근 확인 필요'; message.textContent='공개 정적 페이지에서 REST 응답을 읽지 못해 좌표 기반 관측 구간을 표시합니다.'; } }
renderBusanDetailMap(); refreshOceanStatus();

// 부산 연안만 표시: Google Maps JavaScript API가 설정되면 실제 지도, 미설정 시 부산 상세 대체 지도를 표시합니다.
const nationalReports = busanOceanPoints.map((p) => ({place:`부산 ${p.place}`,region:'부산 연안',lat:p.lat,lng:p.lng,level:p.risk==='high'?'주의':p.risk==='low'?'관찰':'양호',risk:p.risk,species:'해파리 관측',note:p.detail}));
const nationalPinPositions = [[72,22],[61,43],[80,9],[25,80],[45,67],[91,28]];
const googleMapConfig = {apiKey:window.JELLYWATCH_GOOGLE_MAPS_API_KEY || ''};
function nationalReportMarkup(){return `<div class="list-heading"><span>부산 연안 관측 제보</span><span class="mono">${nationalReports.length} COASTS</span></div>`+nationalReports.map((r,i)=>`<article class="report${i===0?' active':''}" data-place="${r.place}" data-level="${r.level}"><div class="report-top"><span class="status ${r.risk}">${r.level}</span><span class="mono">${r.lat.toFixed(4)}°N</span></div><h3>${r.place}</h3><p>${r.species} · ${r.note}</p><div class="report-foot"><span>${r.region}</span><button class="more">상세 보기 ↗</button></div></article>`).join('');}
function renderNationalFallback(map){if(!map)return;const placeTags=['해운대','광안리','송정','다대포','송도','일광'],tagX=[76,66,84,28,48,88],tagY=[18,48,5,86,73,34];map.className='map-canvas busan-only-map national-fallback';map.innerHTML=`<div class="grid-lines"></div><div class="fallback-caption"><strong>부산 연안 상세 관측 지도</strong><span>부산생활지도 기준 · 129°00′E–129°20′E</span></div><div class="map-coordinate coord-n">35°20′N</div><div class="map-coordinate coord-s">35°00′N</div><div class="map-coordinate coord-w">128°55′E</div><div class="map-coordinate coord-e">129°25′E</div><div class="water-label water-east">동해 남부</div><div class="water-label water-west">부산항</div><div class="busan-coast"></div><div class="coast-route"></div>${nationalReports.map((r,i)=>`<button class="national-pin ${r.risk}" style="--x:${nationalPinPositions[i][0]}%;--y:${nationalPinPositions[i][1]}%" data-place="${r.place}" aria-label="${r.place} ${r.level}">${i+1}</button><span class="map-place-tag" style="--x:${tagX[i]}%;--y:${tagY[i]}%">${placeTags[i]}</span>`).join('')}<div class="map-label busan-map-label">부산광역시 연안</div><div class="map-legend"><span><i class="legend-high"></i>주의</span><span><i class="legend-low"></i>관찰</span><span><i class="legend-clear"></i>양호</span></div><div class="map-scale">부산생활지도 기준 <span>6개 관측 구간</span></div>`;bindNationalInteractions();}
function selectNationalReport(place){document.querySelectorAll('.report').forEach(r=>r.classList.toggle('active',r.dataset.place===place));document.querySelector(`.report[data-place="${place}"]`)?.scrollIntoView({behavior:'smooth',block:'nearest'});const item=nationalReports.find(r=>r.place===place);if(window.googleNationalMap&&item){window.googleNationalMap.panTo({lat:item.lat,lng:item.lng});window.googleNationalMap.setZoom(13);}}
function distanceKm(a,b){const rad=Math.PI/180, dLat=(b.lat-a.lat)*rad, dLng=(b.lng-a.lng)*rad, lat1=a.lat*rad, lat2=b.lat*rad;const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
function locateNearestJellyfish(){const status=qs('#apiStatus'),message=qs('#apiMessage');if(status){status.textContent='현재 위치 확인 중';message.textContent='브라우저 위치 권한을 확인하고 가장 가까운 부산 연안 관측 지점을 계산합니다…';}if(!navigator.geolocation){if(status){status.textContent='위치정보를 지원하지 않는 브라우저';message.textContent='지도에서 부산 연안 관측 지점을 직접 선택해 주세요.';}return;}navigator.geolocation.getCurrentPosition((position)=>{const user={lat:position.coords.latitude,lng:position.coords.longitude};const nearest=nationalReports.map((report)=>({...report,distance:distanceKm(user,report)})).sort((a,b)=>a.distance-b.distance)[0];selectNationalReport(nearest.place);drawUserLocation(user);if(status){status.textContent='현재 위치 확인됨';message.textContent=`내 위치에서 가장 가까운 관측 지점은 ${nearest.place}이며 약 ${nearest.distance.toFixed(1)}km 거리입니다.`;}},()=>{if(status){status.textContent='위치 권한을 확인해 주세요';message.textContent='위치 권한이 거부되어 관측 지점을 표시하지 못했습니다. 지도에서 지점을 직접 선택할 수 있습니다.';}},{enableHighAccuracy:true,timeout:10000,maximumAge:300000});}
function drawUserLocation(user){document.querySelector('.user-location')?.remove();const map=qs('.map-canvas');if(window.googleNationalMap&&window.google?.maps){window.jellyWatchUserMarker?.setMap(null);window.jellyWatchUserMarker=new google.maps.Marker({position:user,map:window.googleNationalMap,title:'내 현재 위치',icon:{path:google.maps.SymbolPath.CIRCLE,scale:8,fillColor:'#1769ff',fillOpacity:1,strokeColor:'#fff',strokeWeight:3}});return;}if(!map)return;const minLat=35.02,maxLat=35.29,minLng=128.93,maxLng=129.28;const x=Math.max(4,Math.min(96,(user.lng-minLng)/(maxLng-minLng)*100)),y=Math.max(8,Math.min(92,(maxLat-user.lat)/(maxLat-minLat)*100));const marker=document.createElement('span');marker.className='user-location';marker.style.left=`${x}%`;marker.style.top=`${y}%`;marker.setAttribute('aria-label','내 현재 위치');marker.title='내 현재 위치';map.appendChild(marker);}
function bindNationalInteractions(){document.querySelectorAll('.national-pin').forEach(pin=>pin.addEventListener('click',()=>selectNationalReport(pin.dataset.place)));document.querySelectorAll('.report').forEach(report=>report.addEventListener('click',()=>selectNationalReport(report.dataset.place)));}
function renderGoogleMap(){const map=qs('.map-canvas');if(!map||!window.google?.maps)return;map.className='map-canvas busan-only-map';map.innerHTML='<div id="googleMap" class="google-map-host"></div>';window.googleNationalMap=new google.maps.Map(document.getElementById('googleMap'),{center:{lat:35.16,lng:129.14},zoom:11,minZoom:10,maxZoom:16,streetViewControl:false,fullscreenControl:true,mapTypeControl:true,gestureHandling:'cooperative'});const infoWindow=new google.maps.InfoWindow();nationalReports.forEach((r,i)=>{const marker=new google.maps.Marker({position:{lat:r.lat,lng:r.lng},map:window.googleNationalMap,title:`${r.place} · ${r.note}`,label:{text:String(i+1),color:'#fff',fontWeight:'700'},icon:{path:google.maps.SymbolPath.CIRCLE,scale:14,fillColor:r.risk==='high'?'#f06f58':r.risk==='low'?'#3a9e9a':'#6b8da8',fillOpacity:1,strokeColor:'#fff',strokeWeight:2}});marker.addListener('click',()=>{infoWindow.setContent(`<strong>${r.place}</strong><br><small>${r.note}</small>`);infoWindow.open({anchor:marker,map:window.googleNationalMap});selectNationalReport(r.place);});});}
function updateNationalStatus(connected){const status=qs('#apiStatus'),message=qs('#apiMessage');if(!status)return;if(connected){status.textContent='Google 지도 API 연결됨';message.textContent='부산 연안 6개 관측 구간 · 마커를 눌러 지역별 제보 확인';}else{status.textContent='Google 지도 API 키 확인 필요';message.textContent='API 키가 없거나 인증에 실패해 부산 연안 대체 지도를 표시합니다.';}}
function loadGoogleMap(){const map=qs('.map-canvas');if(!googleMapConfig.apiKey){renderNationalFallback(map);return;}const script=document.createElement('script');script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(googleMapConfig.apiKey)}&loading=async&callback=jellyWatchGoogleMapReady&language=ko&region=KR`;script.async=true;script.defer=true;window.jellyWatchGoogleMapReady=()=>{renderGoogleMap();updateNationalStatus(true);};script.onerror=()=>{renderNationalFallback(map);updateNationalStatus(false);};document.head.appendChild(script);}
function renderNationalMap(){const mapLayout=qs('.map-layout'),map=qs('.map-canvas'),list=qs('.report-list');if(!mapLayout||!map||!list)return;mapLayout.classList.add('busan-only-layout');list.innerHTML=nationalReportMarkup();const bar=qs('.official-data-bar');if(bar){bar.querySelector('.source-link').href='https://lifemap.busan.go.kr/arcgis/rest?f=json';bar.querySelector('.source-link').textContent='부산생활지도 ArcGIS REST ↗';}bindNationalInteractions();loadGoogleMap();}
renderNationalMap();

// 시민 제보: 카메라 촬영/사진 선택 → 위치·메모 입력 → 지도 리포트와 공유
let reportPhoto = '';
let reportStream = null;
const reportPlaces = nationalReports.map(report => report.place);
function esc(value){ return String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch])); }
function injectReportUI(){
  const target = qs('.map-top');
  if(!target || qs('#reportOpen')) return;
  const trigger = document.createElement('button'); trigger.id='reportOpen'; trigger.className='report-trigger'; trigger.innerHTML='📷 제보하기'; target.appendChild(trigger);
  const wrap=document.createElement('div'); wrap.id='reportModal'; wrap.className='report-modal'; wrap.innerHTML=`<div class="report-panel" role="dialog" aria-modal="true" aria-labelledby="reportTitle"><button class="close" id="reportClose">×</button><p class="eyebrow">COMMUNITY REPORT</p><h2 id="reportTitle">해파리를 발견했나요?</h2><p class="report-lead">사진과 위치를 남기면 다른 사람들의 안전한 바다 이용에 도움이 됩니다.</p><div class="capture-box"><video id="cameraPreview" autoplay playsinline></video><img id="photoPreview" alt="선택한 제보 사진 미리보기"><div class="capture-placeholder" id="capturePlaceholder">사진을 촬영하거나<br>앨범에서 선택하세요</div></div><div class="capture-actions"><button class="outline" id="cameraStart">카메라 켜기</button><label class="outline file-label">사진 선택<input id="reportFile" type="file" accept="image/*" capture="environment"></label><button class="outline" id="cameraShot" disabled>촬영하기</button></div><div class="report-fields"><label>발견 위치<select id="reportPlace">${reportPlaces.map(p=>`<option>${p}</option>`).join('')}</select></label><label>위험도<select id="reportLevel"><option value="high">주의</option><option value="low">관찰</option><option value="clear">양호</option></select></label><label>한줄 메모<textarea id="reportNote" maxlength="120" placeholder="예: 해변 동쪽 50m 지점에서 여러 마리 발견"></textarea></label></div><button class="primary full" id="reportSubmit">제보 등록하기 <span>↗</span></button><p class="report-privacy">사진과 제보 내용은 이 브라우저에만 저장됩니다. 공식 관측 데이터로 자동 인정되지는 않습니다.</p></div>`; document.body.appendChild(wrap);
  trigger.addEventListener('click',()=>wrap.classList.add('open')); qs('#reportClose').addEventListener('click',closeReport); wrap.addEventListener('click',e=>{if(e.target===wrap)closeReport();});
  qs('#cameraStart').addEventListener('click',startCamera); qs('#cameraShot').addEventListener('click',takePhoto); qs('#reportFile').addEventListener('change',handlePhotoFile); qs('#reportSubmit').addEventListener('click',submitReport);
}
function closeReport(){ const wrap=qs('#reportModal'); if(reportStream){reportStream.getTracks().forEach(t=>t.stop()); reportStream=null;} wrap?.classList.remove('open'); }
async function startCamera(){ try{ reportStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false}); const video=qs('#cameraPreview'); video.srcObject=reportStream; video.style.display='block'; qs('#cameraShot').disabled=false; qs('#capturePlaceholder').style.display='none'; }catch(e){ alert('카메라를 열 수 없습니다. 사진 선택 버튼을 이용해 주세요.'); } }
function takePhoto(){ const video=qs('#cameraPreview'); if(!video.videoWidth) return; const canvas=document.createElement('canvas'); canvas.width=video.videoWidth; canvas.height=video.videoHeight; canvas.getContext('2d').drawImage(video,0,0); reportPhoto=canvas.toDataURL('image/jpeg',.82); showPhoto(reportPhoto); }
function handlePhotoFile(e){ const file=e.target.files?.[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{reportPhoto=reader.result; showPhoto(reportPhoto);}; reader.readAsDataURL(file); }
function showPhoto(src){ const img=qs('#photoPreview'); img.src=src; img.style.display='block'; qs('#capturePlaceholder').style.display='none'; }
function submitReport(){ const place=qs('#reportPlace').value, level=qs('#reportLevel').value, note=qs('#reportNote').value.trim()||'사진 제보가 등록되었습니다.'; const report={id:Date.now(),place,level,note,photo:reportPhoto,createdAt:new Date().toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}; const saved=JSON.parse(localStorage.getItem('jellywatchReports')||'[]'); saved.unshift(report); localStorage.setItem('jellywatchReports',JSON.stringify(saved.slice(0,20))); addCommunityReport(report); closeReport(); alert('제보가 등록되었습니다. 지도 리포트에서 확인할 수 있습니다.'); }
function addCommunityReport(report){ const list=qs('.report-list'); if(!list) return; const article=document.createElement('article'); article.className='report community-report'; article.dataset.place=report.place; article.innerHTML=`<div class="report-top"><span class="status ${esc(report.level)}">시민 제보</span><span class="mono">${esc(report.createdAt)}</span></div><h3>${esc(report.place)}</h3><p>${esc(report.note)}</p><div class="report-foot"><span>사용자 제보 · 검토 필요</span><button class="more share-report">공유하기 ↗</button></div>`; list.insertBefore(article,list.children[1]||null); article.querySelector('.share-report').addEventListener('click',()=>shareReport(report)); }
async function shareReport(report){ const shareText=`JellyWatch 시민 제보\n${report.place}\n${report.note}\n${location.href}`; try{ if(navigator.share) await navigator.share({title:'JellyWatch 시민 제보',text:shareText,url:location.href}); else { await navigator.clipboard.writeText(shareText); alert('제보 내용이 클립보드에 복사되었습니다.'); } }catch(e){} }
injectReportUI();

// 국립수산과학원 해파리정보 API(jellyList) 기준 5종 분류
const nifsSpecies = [
  {name:'보름달물해파리', latin:'Aurelia aurita', group:'국내 최다 출현', risk:'낮은 위험도', tone:'purple', desc:'우리나라 연안에서 가장 흔하게 관찰되는 종으로, 봄부터 여름 사이 고밀도 출현이 보고됩니다.'},
  {name:'노무라입깃해파리', latin:'Nemopilema nomurai', group:'대형 유입종', risk:'높은 위험도', tone:'orange', desc:'동중국해에서 해류를 따라 유입되는 대형 종으로, 해수욕장과 어장 피해를 유발할 수 있습니다.'},
  {name:'작은부레관해파리', latin:'Physalia physalis', group:'독성 부유종', risk:'높은 위험도', tone:'yellow', desc:'푸른 부레와 긴 촉수가 특징인 종입니다. 해변에 떠밀려온 개체도 맨손으로 만지지 마세요.'},
  {name:'유령해파리', latin:'Cyanea nozakii', group:'남해·동해남부', risk:'높은 위험도', tone:'blue', desc:'따뜻한 해역을 중심으로 출현하는 대형 종으로, 촉수 접촉 시 쏘임 사고를 일으킬 수 있습니다.'},
  {name:'커튼원양해파리', latin:'Chrysaora pacifica', group:'연안 독성종', risk:'관찰 필요', tone:'teal', desc:'우리나라 연안 모니터링에서 확인되는 독성 해파리류로, 출현 지역에서는 거리를 두어야 합니다.'}
];
species.splice(0, species.length, ...nifsSpecies.map(s=>`${s.name} — ${s.desc}`));
function renderNifsSpecies(){
  const grid=qs('.species-grid'); if(!grid) return;
  grid.innerHTML=nifsSpecies.map((s,i)=>`<article class="species-card nifs-card ${s.tone}"><div class="species-num">0${i+1} / 05</div><div class="nifs-medusa">◌</div><span class="nifs-group">${s.group}</span><h3>${s.name}</h3><p>${s.latin}</p><span class="risk-tag">${s.risk}</span></article>`).join('');
  const section=qs('#species'); if(section&&!qs('#nifsSourceBar')){const bar=document.createElement('div');bar.id='nifsSourceBar';bar.className='nifs-source-bar';bar.innerHTML='<div><span class="api-dot"></span><strong id="nifsApiStatus">국립수산과학원 해파리정보 API 기준</strong><p id="nifsApiMessage">jellyList · 국내 연안 주간 모니터링 대상 5종 분류</p></div><a class="source-link" href="https://www.nifs.go.kr/openApi/actionOpenapiInfoList.do?contentsCd=06" target="_blank" rel="noopener">API 명세 보기 ↗</a>';section.appendChild(bar);}
}
function refreshNifsStatus(){const status=qs('#nifsApiStatus'),message=qs('#nifsApiMessage');if(!status)return;const hasKey=window.JELLYWATCH_NIFS_KEY||localStorage.getItem('jellywatchNifsKey');if(hasKey){status.textContent='국립수산과학원 API 연결 설정됨';message.textContent='jellyList 실시간 호출 준비 완료 · 키는 서버 프록시에서 관리하세요.';}else{status.textContent='국립수산과학원 API 기준 5종 분류';message.textContent='실시간 jellyList 호출은 발급받은 인증키와 서버 프록시 연결 후 활성화됩니다.';}}
renderNifsSpecies(); refreshNifsStatus();
